Repository CCDirectLink/crosscode-map-editor, pull requests merged in 2019-08, with the labels that each got.

#62 Add a map selector
  backend/src/server.ts
  common/src/controllers/api.ts
  webapp/src/app/app.module.ts
  webapp/src/app/components/editor/editor.component.html
  webapp/src/app/components/editor/editor.component.scss
  webapp/src/app/components/editor/editor.component.ts
  webapp/src/app/components/load-map/load-map.component.html
  webapp/src/app/components/load-map/load-map.component.scss
  webapp/src/app/components/load-map/load-map.component.ts
  webapp/src/app/components/load-map/mapNode.model.ts
  webapp/src/app/components/load-map/virtualMapNode.model.ts
  webapp/src/app/components/toolbar/toolbar.component.html
  webapp/src/app/components/toolbar/toolbar.component.scss
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/external-modules/material.module.ts
  webapp/src/app/services/http-client.service.ts
  webapp/src/app/shared/map-loader.service.ts
  webapp/src/styles.scss
Labels: enhancement

#66 Height generator + autotiles
  webapp/src/app/components/phaser/phaser.component.ts
  webapp/src/app/components/toolbar/toolbar.component.html
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/services/autotile/autotile.constants.ts
  webapp/src/app/services/autotile/autotile.service.ts
  webapp/src/app/services/autotile/gfx-mapper.ts
  webapp/src/app/services/height-map-generator.service.ts
  webapp/src/app/services/height-map/gfx-mapper/gfx-mapper.constants.ts
  webapp/src/app/services/height-map/gfx-mapper/gfx-mapper.ts
  webapp/src/app/services/height-map/height-map.service.ts
  webapp/src/app/services/height-map/heightmap.constants.ts
  webapp/src/app/shared/global-events.service.ts
  webapp/src/app/shared/globals.ts
  webapp/src/app/shared/phaser/helper.ts
  webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
  webapp/src/app/shared/phaser/tilemap/fill.ts
  webapp/src/app/shared/phaser/tilemap/tile-drawer.ts
  webapp/src/assets/autotiles.json
  webapp/src/assets/definitions.json
  webapp/src/assets/tilesets.json
  webapp/src/styles.scss
Labels: WIP

#73 Fixed layer resize overriding unsaved data
  webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
Labels: bug, resolves

#72 Fixed multiple instances causing errors
  webapp/main.js
  webapp/package-lock.json
  webapp/package.json
Labels: bug, resolves

#82 Added descriptions to readme
  README.md
Labels: enhancement

#76 add "save" and "save as..."
  CHANGELOG.md
  backend/package-lock.json
  backend/src/server.ts
  common/src/controllers/api.ts
  common/src/controllers/saveFile.ts
  webapp/nwjs/package.json
  webapp/package-lock.json
  webapp/src/app/components/toolbar/toolbar.component.html
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/models/cross-code-map.ts
  webapp/src/app/services/http-client.service.ts
  webapp/src/app/services/save.service.ts
  webapp/src/app/shared/map-loader.service.ts
  webapp/src/app/shared/path-resolver.ts
  webapp/src/app/shared/phaser/tilemap/cc-map.ts
Labels: enhancement, resolves

#86 Fixed wrong regex in path resolver
  webapp/src/app/shared/path-resolver.ts
Labels: bug
