Repository CCDirectLink/crosscode-map-editor, pull requests merged in 2020-12, with the labels that each got.

#196 Changed Continuous Integration to Github Actions
  .github/workflows/build.yml
  .travis.yml
  CHANGELOG.md
Labels: internal, resolves

#198 automate release process
  .github/actions/build/action.yml
  .github/workflows/build.yml
  .github/workflows/prepare_release.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: bump:minor

#199 try auto release again
  CHANGELOG.md
Labels: bump:patch

#200 remove build status badge and fix pr check
  .github/workflows/pull_request.yml
  README.md
Labels: Skip-Changelog, documentation
