Repository CCDirectLink/crosscode-map-editor, pull requests merged in 2020-09, with the labels that each got.

#144 add 3d preview
  CHANGELOG.md
  webapp/.editorconfig
  webapp/angular.json
  webapp/karma.conf.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/app-routing.ts
  webapp/src/app/app.module.ts
  webapp/src/app/components/babylon/babylon.component.html
  webapp/src/app/components/babylon/babylon.component.scss
  webapp/src/app/components/babylon/babylon.component.ts
  webapp/src/app/components/editor/editor.component.html
  webapp/src/app/components/editor/editor.component.scss
  webapp/src/app/components/entities/entities.component.html
  webapp/src/app/components/entities/entities.component.ts
  webapp/src/app/components/floating-window/floating-window.component.html
  webapp/src/app/components/floating-window/floating-window.component.ts
  webapp/src/app/components/phaser/phaser.component.ts
  webapp/src/app/components/sidenav/sidenav.component.html
  webapp/src/app/components/sidenav/sidenav.component.ts
  webapp/src/app/components/tile-selector/tile-selector.component.ts
  webapp/src/app/components/toolbar/toolbar.component.html
  webapp/src/app/components/toolbar/toolbar.component.scss
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/external-modules/material.module.ts
  webapp/src/app/shared/3d/BabylonViewer.ts
  webapp/src/app/shared/3d/camera/custom-free-camera.ts
  webapp/src/app/shared/3d/camera/wasd-cam-input.ts
  webapp/src/app/shared/3d/debug/show-axis.ts
  webapp/src/app/shared/3d/debug/toggle-mesh.ts
  webapp/src/app/shared/3d/entities/entity-generator.ts
  webapp/src/app/shared/3d/entities/entity-manager-3d.ts
  webapp/src/app/shared/3d/layer-generation/boundary-tracing/boundary-tracer.spec.ts
  webapp/src/app/shared/3d/layer-generation/boundary-tracing/boundary-tracer.ts
  webapp/src/app/shared/3d/layer-generation/boundary-tracing/node-grid.ts
  webapp/src/app/shared/3d/layer-generation/layer-mesh-generator.spec.ts
  webapp/src/app/shared/3d/layer-generation/layer-mesh-generator.ts
  webapp/src/app/shared/3d/layer-generation/offset-helper.ts
  webapp/src/app/shared/3d/layer-generation/side-mesh-generator.ts
  webapp/src/app/shared/3d/layer-generation/simple-tile-layer.ts
  webapp/src/app/shared/3d/layer-generation/texture-generator.ts
  webapp/src/app/shared/3d/ui/wireframe.ts
  webapp/src/app/shared/global-events.service.ts
  webapp/src/app/shared/history/history.component.html
  webapp/src/app/shared/history/history.component.ts
  webapp/src/app/shared/map-loader.service.ts
  webapp/src/app/shared/phaser/entities/cc-entity.ts
  webapp/src/app/shared/phaser/entities/entity-manager.ts
  webapp/src/app/shared/phaser/entities/registry/default-entity.ts
  webapp/src/app/shared/phaser/main-scene.ts
  webapp/src/app/shared/phaser/phaser-events.service.ts
  webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
  webapp/src/app/shared/phaser/tilemap/cc-map.ts
  webapp/src/app/shared/phaser/tilemap/tile-drawer.ts
  webapp/src/app/tests/map-loading.spec.ts
  webapp/src/test.ts
  webapp/src/tsconfig.spec.json
  webapp/tsconfig.json
Labels: dependencies, enhancement

#175 Move dependencies to dev
  CHANGELOG.md
  README.md
  webapp/package-lock.json
  webapp/package.json
Labels: dependencies, internal

#182 Fixed flip offset
  webapp/src/app/shared/phaser/entities/cc-entity.ts
Labels: bug, internal, resolves

#179 Layer bugfix
  CHANGELOG.md
  webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
  webapp/src/app/tests/layers.spec.ts
Labels: bug, internal, resolves
