Repository CCDirectLink/crosscode-map-editor, pull requests merged in 2023-08, with the labels that each got.

#253 Fix langlabel widget not resizing
  CHANGELOG.md
  webapp/src/app/directives/resized.directive.ts
Labels: bump:patch

#298 moved manual input outside of image select widget
  webapp/src/app/app.module.ts
  webapp/src/app/components/widgets/character-widget/character-widget.component.html
  webapp/src/app/components/widgets/character-widget/character-widget.component.ts
  webapp/src/app/components/widgets/custom-des-type-widget/custom-des-type-widget.component.html
  webapp/src/app/components/widgets/enemy-single-type-widget/enemy-single-type-widget.component.html
  webapp/src/app/components/widgets/enemy-single-type-widget/enemy-single-type-widget.component.ts
  webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.html
  webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.scss
  webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.ts
  webapp/src/app/services/phaser/entities/registry/item-destruct.ts
Labels: Skip-Changelog

#299 combined pull requests
  CHANGELOG.md
  webapp/src/app/app.module.ts
  webapp/src/app/components/dialogs/offset-map/offset-map.component.html
  webapp/src/app/components/dialogs/offset-map/offset-map.component.ts
  webapp/src/app/components/layers/layers.component.html
  webapp/src/app/components/layers/layers.component.scss
  webapp/src/app/components/layers/layers.component.ts
  webapp/src/app/components/phaser/phaser.component.ts
  webapp/src/app/components/sidenav/sidenav.component.ts
  webapp/src/app/components/toolbar/toolbar.component.html
  webapp/src/app/components/toolbar/toolbar.component.scss
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/components/widgets/character-widget/character-widget.component.html
  webapp/src/app/components/widgets/character-widget/character-widget.component.ts
  webapp/src/app/components/widgets/custom-des-type-widget/custom-des-type-widget.component.html
  webapp/src/app/components/widgets/enemy-single-type-widget/enemy-single-type-widget.component.html
  webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.html
  webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.scss
  webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.ts
  webapp/src/app/components/widgets/overlay-widget.ts
  webapp/src/app/components/widgets/person-expression-widget/custom-expression-widget/custom-expression-widget.component.html
  webapp/src/app/components/widgets/person-expression-widget/custom-expression-widget/custom-expression-widget.component.scss
  webapp/src/app/components/widgets/person-expression-widget/custom-expression-widget/custom-expression-widget.component.ts
  webapp/src/app/components/widgets/person-expression-widget/custom-expression-widget/expression-renderer-entity.ts
  webapp/src/app/components/widgets/person-expression-widget/person-expression-widget.component.html
  webapp/src/app/components/widgets/prop-type-widget/prop-type-widget.component.ts
  webapp/src/app/components/widgets/shared/image-select-overlay/image-select-card/image-select-card.component.scss
  webapp/src/app/components/widgets/shared/image-select-overlay/image-select-list/image-select-list.component.html
  webapp/src/app/components/widgets/shared/image-select-overlay/image-select-overlay.component.html
  webapp/src/app/components/widgets/shared/image-select-overlay/image-select-overlay.component.ts
  webapp/src/app/components/widgets/shared/image-select-overlay/variables.scss
  webapp/src/app/models/cross-code-map.ts
  webapp/src/app/services/3d/layer-generation/texture-generator.ts
  webapp/src/app/services/global-events.service.ts
  webapp/src/app/services/phaser/base-object.ts
  webapp/src/app/services/phaser/entities/cc-entity.ts
  webapp/src/app/services/phaser/entities/registry/item-destruct.ts
  webapp/src/app/services/phaser/helper.ts
  webapp/src/app/services/phaser/ingame-preview.ts
  webapp/src/app/services/phaser/layer-parallax.ts
  webapp/src/app/services/phaser/main-scene.ts
  webapp/src/app/services/phaser/map-pan.ts
  webapp/src/app/services/phaser/phaser-events.service.ts
  webapp/src/app/services/phaser/pre-update.ts
  webapp/src/app/services/phaser/tilemap/cc-map-layer.ts
  webapp/src/app/services/phaser/tilemap/cc-map.ts
  webapp/src/app/services/phaser/tilemap/tile-drawer.ts
  webapp/src/assets/abstract-faces.json
  webapp/src/assets/ingame.png
Labels: enhancement, resolves, bump:minor

#282 add support for different layer sizes
  CHANGELOG.md
  webapp/src/app/components/layers/layers.component.html
  webapp/src/app/components/layers/layers.component.scss
  webapp/src/app/components/layers/layers.component.ts
  webapp/src/app/components/phaser/phaser.component.ts
  webapp/src/app/components/sidenav/sidenav.component.ts
  webapp/src/app/components/toolbar/toolbar.component.html
  webapp/src/app/components/toolbar/toolbar.component.scss
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/services/3d/layer-generation/texture-generator.ts
  webapp/src/app/services/global-events.service.ts
  webapp/src/app/services/phaser/base-object.ts
  webapp/src/app/services/phaser/ingame-preview.ts
  webapp/src/app/services/phaser/layer-parallax.ts
  webapp/src/app/services/phaser/main-scene.ts
  webapp/src/app/services/phaser/map-pan.ts
  webapp/src/app/services/phaser/phaser-events.service.ts
  webapp/src/app/services/phaser/pre-update.ts
  webapp/src/app/services/phaser/tilemap/cc-map-layer.ts
  webapp/src/app/services/phaser/tilemap/cc-map.ts
  webapp/src/app/services/phaser/tilemap/tile-drawer.ts
  webapp/src/assets/ingame.png
Labels: bump:minor

#283 added checkbox to "Offset Map" to optionally include entities
  CHANGELOG.md
  webapp/src/app/components/dialogs/offset-map/offset-map.component.html
  webapp/src/app/components/dialogs/offset-map/offset-map.component.ts
  webapp/src/app/components/toolbar/toolbar.component.ts
  webapp/src/app/services/global-events.service.ts
  webapp/src/app/services/phaser/entities/cc-entity.ts
  webapp/src/app/services/phaser/tilemap/cc-map.ts
Labels: bump:patch
