Repository CCDirectLink/crosscode-map-editor, pull requests merged in 2023-09, with the labels that each got.

#303 Added confirm close dialog
  CHANGELOG.md
  webapp/src/app/app.component.ts
  webapp/src/app/app.module.ts
  webapp/src/app/components/dialogs/confirm-close/confirm-close.component.html
  webapp/src/app/components/dialogs/confirm-close/confirm-close.component.scss
  webapp/src/app/components/dialogs/confirm-close/confirm-close.component.ts
  webapp/src/app/components/dialogs/floating-window/history/state-history.service.ts
  webapp/src/app/components/dialogs/load-map/load-map.component.ts
  webapp/src/app/components/dialogs/overlay/overlay-ref-control.ts
  webapp/src/app/components/dialogs/overlay/overlay.service.ts
  webapp/src/app/external-modules/material.module.ts
  webapp/src/app/services/global-events.service.ts
  webapp/src/app/services/save.service.ts
Labels: enhancement, resolves, bump:patch

#308 Reset hasUnsavedChanges on discard
  CHANGELOG.md
  webapp/src/app/components/dialogs/load-map/load-map.component.ts
Labels: bug, resolves, bump:patch

#304 Ignore mod when JSON errors accur in package.json
  CHANGELOG.md
  common/src/controllers/api.ts
Labels: bump:patch

#305 Fix entity size overrides
  CHANGELOG.md
  webapp/src/app/services/phaser/entities/cc-entity.ts
Labels: bump:patch
